language: node_js
node_js: '13'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '13'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'dGskAxOtygg1EHVGkrAuWx+fFYada0wHu8hs/t2xPREbZQzx4SjdtJV3Pt/zYAKfU/vpgu8/l3UyaEWWS893VYvDVtIKYKMNcYR48nda75/k7xmAFhKzZ54e9etdKXGHtTLqys4PG0jXEqrIP+t6ktNV3wzH0mfulH7EfZJX8RHJvICnN3kVUIP5a3afPQ4s0LCBZ95XUsUEtQuooDDZyN746a9zG6h8nUAIxpJm8HlsUoBhhr5jEL2QqKFaMcvcNFPybruoWF6MjSCJAkZXTPlvn0ntPKJSS0B9AWSMsnnNubyxtzjxR+VzXPdeXAnES7EHm6nUXJNCb0VDXA8DsHBCu+6ya8F42f9JtnMSlo8sks8Bilw26z3Yh9BgAFBVIH2sTurMEGYAmedLvxrEjWx9HYI4kF3oar9itwZfeNJzTHfVusHCG7u3Zkt+ki2iESrfRxKTQF4f/odTWLSlcCrtAkf6OKaMYSQid9msbFUunn993YvwP0bttWTCBriBPd6T7km7eD0U9yBoqjWcpxDTVjCa+atIFDcjvU9226wco7V4b2wiuHgDUt0P7GCDZDBiGmIkpFtrSEgd7OLNdciObKnqGZqSeC9lyG3kWaoi0yI+XJfGHQXohb+Q12zaiyKLBO2MufS1wkZuQqWjzFS7MpQHyj0dcPXphx3CHZo='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
